languages = ["Abanasinian",
             "Abyssal",
             "Celestial",
             "Common",
             "Daelkyr",
             "Deep Speech",
             "Dwarvish",
             "Draconic",
             "Elvish",
             "Ergot",
             "Giant",
             "Gith",
             "Gnomish",
             "Goblin",
             "Halfling",
             "Hadozee",
             "Infernal",
             "Istarian",
             "Kenderspeak",
             "Kharolian",
             "Khur",
             "Kothian",
             "Kraul",
             "Kuo-Toan",
             "Leonin",
             "Loxodon",
             "Marquesian",
             "Minotaur",
             "Naush",
             "Nerakese",
             "Nordmaarian",
             "Ogre",
             "Orc",
             "Primordial",
             "Quori",
             "Riedran",
             "Sahuagin",
             "Solamnic",
             "Sylvan",
             "Thri-kreen",
             "Undercommon",
             "Vedalken",
             "Zemnian"]

abilities = ["Strength",
             "Dexterity",
             "Constitution",
             "Intelligence",
             "Wisdom",
             "Charisma"]

skills = ["Acrobatics",
          "Animal Handling",
          "Arcana",
          "Athletics",
          "Deception",
          "History",
          "Insight",
          "Intimidation",
          "Investigation",
          "Medicine",
          "Nature",
          "Perception",
          "Performance",
          "Persuasion",
          "Religion",
          "Sleight of Hand",
          "Stealth",
          "Survival"]

feats = ["Great Weapon Master", "Skill Expert", "Tough"]
